### ISSUE TITLE
CSVs are being appended to in subsequent runs

### ISSUE THREAD

**Issue by sebbacon** [opensafely/cohort-extractor#220]

**Comment by evansd** [comment]
This is because we open the file in `a+` mode here: https://github.com/opensafely/cohort-extractor/blob/45cc2db0efb4430f67516f15c943ad7461cd2ea4/cohortextractor/mssql_utils.py#L104-L109

I copied this directly from your original code @sebbacon when I factored this into a library function. Do you remember why you did this? It's the sort of thing that looks like quite a deliberate decision, but it may be that the reason behind it no longer applies.

**Comment by sebbacon** [comment]
I think this was probably a lazy way to open the file in read/write mode (for the `seek` behaviour later) *and* create it if it didn't exist.

**Comment by evansd** [comment]
Ah, of course, yes. `w+` is what you want I think.
