### ISSUE TITLE
Unexpected cohort size - school age children

### ISSUE THREAD

**Issue by sebbacon** [opensafely/cohort-extractor#276]
Like #272, another study has seen a similar "halving" effect. @hjforbes  says:

> the previous extract had >4million under 18s in it, whilst this extract has around 1.8million... The only change from the previous study def I made was adding ICU data, so that shouldn't have affected it.  So either I've introduced some other criteria accidentally into the study definition, or something went wrong when the data were extracted? ... I've looked at changes to the study definition file since 6th August (when there were ~2mill more kids in the extract) and I can't see amendments which would cause them to drop

[This is the study definition in question](https://github.com/opensafely/school-age-children-and-covid/commits/run22aug/analysis/study_definition.py) 

The extract with the problem is at `E:/analyses/school-age-children-and-covid/outputs/input.csv`, with a timestamp of 20:51 on 17 Aug

**Comment by sebbacon** [comment]
That extract contains ~20 million rows with ~2.2m aged 18 and under.  Odd that @hjforbes sees ~1.8m, but in either case that's way short of ~4m.

**Comment by sebbacon** [comment]
Without the CSV that contained ~4m rows all we can really do is kick off another cohort generation.

**Comment by hjforbes** [comment]
okay - @CarolineMorton is checking that changes made to the study definition won't have led to some under18s being dropped - assuming you don't find anything Caroline, can you kick off another extract?

**Comment by CarolineMorton** [comment]
I have checked the study definition from [20 days ago](https://github.com/opensafely/school-age-children-and-covid/blob/a27d3907a1814a7b1a5c7422c3740ad29458754c/analysis/study_definition.py) and [this week](https://github.com/opensafely/school-age-children-and-covid/blob/run22aug/analysis/study_definition.py)

**Differences spotted:**

1. on_or_after="2020-02-01", added and changed from on_or_before="2020-08-01" can't see how that would make much of a difference except b adding in a few more weeks depending on when extract was
2. covid_icu_date=patients.admitted_to_icu() added but can see no obvious errors to why this would restrict cohort
3. positive_covid_test_ever=patients.with_test_result_in_sgss() added but ditto as above

I am unclear why this would restrict the population. I do wonder if it is possible that the cohort extract just stopped due to an interruption with the db or something else and it just wasn't obvious.

**Comment by sebbacon** [comment]
@CarolineMorton started another extract last night, and it exited with an error about duplicates.  This would explain why the dataset was truncated - though to work as an explanation it needs people not to have noticed any error messages, which I think is plausible.

**Comment by sebbacon** [comment]
Have just kicked off a new extract for this study on the server. If we get the expected number of rows this issue can be closed.

**Comment by sebbacon** [comment]
The output generated yesterday completed without an error, with 23m rows and 4.7m aged 18 or under
