### ISSUE TITLE
Error conditions should not leave partial CSVs around

### ISSUE THREAD

**Issue by sebbacon** [opensafely/cohort-extractor#278]
In the case of #277, it seems that users didn't notice error conditions and went ahead with using partial cohorts.

If there's a cohort generation error, the CSV should be deleted to avoid this.

**Comment by evansd** [comment]
I think we originally made a deliberate decision _not_ to do this because the extractions sometimes take so long and it was useful, both for debugging purposes and for the sake of having something to develop the next stage of the pipeline against, to have even a partial file. Obviously the downside is the linked issue.

But it now strikes me that if we just make sure the partial file has a different name (one which makes it obvious that there's an issue with it) then we get the best of both worlds.

**Comment by sebbacon** [comment]
Good thinking +1000
