### ISSUE TITLE
APCS Discharge date needed for thrombotic events

### ISSUE THREAD

**Issue by johntaz** [opensafely/cohort-extractor#296]
For the thrombotic events work we would need to use the discharge date (and other available dates) in the APCS data. 
Would it be possible to add this to the cohort-extractor? What level of date granularity will be available i.e. date_format = "yyyy-mm-dd" or include_month = TRUE? 

@inglesp @ghickman @sebbacon @alexwalkercebm

**Comment by sebbacon** [comment]
We'll need to draw up a spec for this explaining the context for this: which APCS data columns, what for, etc.

Dev team unlikely to get time to address this for a week or so; @wjchulme might have time to help write this up as a spec in the mean time?

**Comment by wjchulme** [comment]
Should be a simple one just using `discharge_date` in the `APCS` table, but will need to sense-check results against other dates and presumably discharge location is also required. Will take a look tomorrow

**Comment by wjchulme** [comment]
Turns out we can already




An overview: In HES-speak, a "spell" is a collection of "episodes" (often just one episode) denoting the entirety of a patient's stay in hospital from admission to discharge or death. An episode denotes time within a spell spent under the responsibility of a single consultant. So for example if within your hospital stay you are transferred from a medical to surgical ward, or transferred to another hospital, you will have at least two episodes within your spell. 

So to ensure each discharge date extraction each admission and discharge date should be linked to an inpatient spell, rather than querying admission dates or discharge dates directly (eg first in period or last in period). Just so that we know the admission date and discharge date (+ any anything else) are part of the same spell.

As such, I don't _think_ that if we repurposed the [`patients.admitted_to_hospital()` code](https://github.com/opensafely/cohort-extractor/blob/da036416bbb2f55bb4fbbca1b791acdf16f0f2d1/cohortextractor/tpp_backend.py#L1537) to spit out discharge date instead that it would necessarily always match the admission date. eg with a patient had two spells in hospital from `2020-02-28 - 2020-03-01` and `2020-03-15 - 2020-03-16`, then 



would give `admission_date > discharge_date` if we didn't tie `patients.discharged_from_hospital` to the admission date.

Assuming that if we want discharge date then we always also want admission date, then an appropriate API is probably 

```
    admission_date = patients.admitted_to_hospital(
        returning = "admission_date",
        ...
    ),
    discharge_date = patients.admitted_to_hospital(
        returning = "discharge_date",
        ...
    )
```

**Comment by alexwalkercebm** [comment]
The point about getting the admission/discharge date for the same spell is an important one, as for our thrombosis study we'll be wanting to work out the length of stay in hospital. Should be possible as it looks like `APCS_Ident` is a unique identifier for each spell?

**Comment by wjchulme** [comment]
I didn't realise this when you asked earlier (sorry!) but it turns out we can already get discharge date from [`patients.admitted_to_hospital()` code](https://github.com/opensafely/cohort-extractor/blob/da036416bbb2f55bb4fbbca1b791acdf16f0f2d1/cohortextractor/tpp_backend.py#L1537) using `returning= "date_discharged"`. 

However, I'm not sure exactly how it deals with patients who haven't been discharged after the last query date. So for example if we did something like
```
    admission_date = patients.admitted_to_hospital(
        between =["2020-03-01", "2020-06-01"],
        returning = "date_admitted",
        find_last_match_in_period=True,
        ...
    ),
    discharge_date = patients.admitted_to_hospital(
        between =["2020-03-01", "2020-06-01"],
        returning = "date_discharged",
        find_last_match_in_period=True,
        ...
    )
```
with a patient had two spells in hospital from `2020-05-01 - 2020-05-14` and `2020-05-30 - 2020-06-02`, then `admission_date="2020-05-30"`, but does `discharge_date` equal `null`, `"2020-06-02"` or (a bug) `"2020-05-14"`? @inglesp can you confirm?

@johntaz if you can extract discharge dates as above in a study def then we can close this issue.

**Comment by alexwalkercebm** [comment]
I agree that we can close. I'm fairly sure that it would return `"2020-06-02"` as it would return the discharge date from the row corresponding to the `MAX` admission date within `between`.

Perhaps might be nice to query discharge date with `between` too, but that's a separate issue and not needed for now.

**Comment by sebbacon** [comment]
Is it worth capturing some of this conversation in more "official" documentation?

**Comment by wjchulme** [comment]
What about a patient with `2020-05-01 - 2020-05-14` and `2020-05-30 - null` spells, where discharge date for the last spell is `null` because they're still in hospital? Wouldn't it then be `2020-05-14`?

**Comment by wjchulme** [comment]
@sebbacon is there a use to putting these sort of explanations directly in `patients.py`? It would maybe be make it annoyingly long, but then info is all in the same place and it's ready to be `pydoc`ed if/when the time comes. It also means it can be properly reviewed if I get something wrong.

**Comment by evansd** [comment]
I think the `patients.py` comments should contain enough detail so that a reader can fully understand what the function does, but it doesn't necessarily need to contain the full discussion that led to that. However it's always worth sticking in link to the discussion.
