### ISSUE TITLE
Get TPP/Total MSOA population

### ISSUE THREAD

**Issue by wjchulme** [opensafely/cohort-extractor#301]
Requested for carehomes study so that patients can be excluded if the proportion of TPP-registered residents in a given MSOA is below a certain threshold. 

The total MSOA population is based on 2019 mid-year (30 June) estimates from ONS (see https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/middlesuperoutputareamidyearpopulationestimates) and is available in the database in the `MSOA_PopulationEstimates_2019` table. TPP MSOA population can be estimated from the `Household` table.

Probably right that this goes in its own extractor function as there's nothing else returning a variable at this level. Something like

```
MSOA_tpp_proportion = patients.MSOA_ttp_proportion_as_of(
    date = "2019-06-30",
)
```
where `2019-06-30` is the only current valid date. 

The SQL will be something like this:

```
SELECT
	p.Patient_ID AS patient_id,
	h.TppProportion
FROM
(
	SELECT 
		hhm.Patient_ID,
		--hhm.Household_ID,
		hh.MSOA
	FROM HouseholdMember AS hhm
	INNER JOIN
	Household AS hh
	ON hh.Household_ID=hhm.Household_ID
) AS p
INNER JOIN
(
	SELECT 
		hh.MSOA, 
		CAST(hh.TppPopulation AS FLOAT)/CAST(ons.Age_All AS FLOAT) AS TppProportion
	FROM (
		SELECT MSOA, SUM(HouseholdSize) as TppPopulation
		FROM Household
		GROUP BY MSOA
		) AS hh
	LEFT JOIN (
		SELECT MSOA_code, Age_All
		FROM MSOA_PopulationEstimates_2019
		) AS ons
	ON hh.MSOA = ons.MSOA_code
) AS h
ON h.MSOA=p.MSOA
```

There may be a more succint / efficient way to do this!

Sometimes the proportion is greater than zero, at least partly because the total population from ONS is out-of-date compared with the tpp population. This isn't a big deal given the intended use. 

There is a potential disclosivity issue. MSOA populations are always within about 5,000 to 12,000 (by design). And sometimes the TPP population is 1 or 2. This would lead to a proportion of, say, `1/5000`. You could then derive the patient's MSOA if it was the only MSOA with a population of `5000` and there were no MSOAs with a population of exactly `10000` (=`2/1000`, the only other possible way to get that proportion given the range of MSOA populations). MSOA is pseudonymised at level 3 but this potentially breaches that. An easy way around this is to round the proportion to 2 or 3 decimal places.

**Comment by wjchulme** [comment]
Aha. This is quite a niche variable request so if it can be done outside of a study def then that makes sense. It would mean putting MSOA total population estimates in a repo somewhere to pull into the server (it's already in the DB but unless you can pull it via a study def then that's no good) but as @Seb says this makes it easier to maintain externally. 

One reason to do it this way is that the variable is needed for cohort selection, so it would reduce redundancy in extracted data and speed up extracts. Without it you'd need to extract _all_ patients to get the right TPP population estimates, regardless of what the intended analytic cohort is (though you could do this is a seperate study def that just extracts MSOA).

**Comment by evansd** [comment]
I'm a bit torn here. I'm all for making the cohortextractor code (and my life) as simple as possible. But then keeping data extraction to the minimum possible is a core OpenSAFELY principle and this does make a dramatic difference on that score.

I think I'm inclined to try to do this all within the study definition. The MSOA population estimates are such a tiny dataset that we could just bundle them with the cohortextractor if it turned out that keeping them up-to-date within the EHR providers was too much of a problem.

**Comment by evansd** [comment]
Right. Having gone in circles a few times I now think this is best done outside of the study definition because the complexity and potential fragility it introduces there is too great, and because I think it can be sensibly done using the `project.yaml` specification.

What I'm imaging is something like this:
 * There's a main study definition which pulls out the population and variables needed for the study, along with MSOA for each patient in the study population.
 * There's another study definition which just pulls out MSOA and household size for every patient in the db.
 * There a script (Stata, Python, R whatever) which takes the results of this second cohort and the ONS population estimates (which can just be committed as CSV in the repo) and produces a CSV table giving the estimated proportion of TPP patients for each MSOA.
 * There's a filter script which takes the main study cohort and the MSOA table and just removes any patients whose MSOA is below some predefined threshold, outputting the filtered cohort.
 * The rest of the analytic pipeline can just proceed using this filtered cohort.

Expressing these sorts of dependent steps is exactly what the `project.yaml` file is for and I think that's the best way of keeping the complexity manageable.

**Comment by wjchulme** [comment]
This is a fairly standard bit of merge+filter data wrangling but I think it's important to set a precedent for how these sorts of problems should be handling in future. And I think the removing dependencies on backend work is important. So I agree this is the right approach!

**Comment by evansd** [comment]
Sorry yes, didn't mean to imply that you needed me to explain how to do it! I just needed to spell it out to convince myself that it could all be done neatly through the `project.yaml` pipeline, rather than being something that would be needed to done ad hoc for every study that wanted to use this data.

**Comment by sebbacon** [comment]
Yes this is indeed exactly the sort of workflow I had in mind originally, so I'm delighted you've identified use-case for it!

My vague thought is that common filters like this could eventually themselves be packaged into standard actions that we ship for people though I'm not sure if that'd actually be that useful or not.

**Comment by evansd** [comment]
I'm going to close this ticket as the following now works:
```
patients.household_as_of("<date>", returning="msoa")
```
@wjchulme Feel free to re-open or create a new ticket if you think there's more work needed from us.

**Comment by wjchulme** [comment]
This raises an issue for dummy data if MSOA is part of data-processing step and not just an input for a statistical model. There are loads of MSOAs. Rather than specifying all of these by hand with `return_expectations={"category": {"ratios": {"MSOA1": 0.01, "MSOA2": 0.01, ...}}`, if it's instead possible to pass in a pre-defined dictionary of MSOAs that would make things a lot simpler. Same for eg ethnicity, STP and others. 

I could have a go at creating a dict of dicts for some of the most common categorical variables that can be shipped with `cohortextractor`?

**Comment by evansd** [comment]
I think there are a few ways of tackling this kind of problem, with pre-baked dictionaries being one of them. Let's open a new ticket to discuss.
