### ISSUE TITLE
-f command not recognised

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely/cohort-extractor#394]
I was trying to re-run vaccine notebook again, and ran into what seems to be two issues. 

What I was trying to do: Re-run the study def again to see if same error

1) The `--help` suggests running `--force-run` to achieve this. This however does not work and you get:
`=> All actions already completed successfully.  Use -f option to force everything to re-run`

2) Running with `-f` gets this error:
`cohortextractor: error: unrecognized arguments: -f`

**Comment by evansd** [comment]
Ah yeah, this is a bit confusing because the error message assumes you're using the `opensafely run` command rather than the `cohortextractor`. I think you can get the same effect from the cohortextractor by using `--force-run --force-run-dependencies`. But it might be preferable to use the `opensafely run` command in any case.
