### ISSUE TITLE
Safe export of analytic outputs from the secure server

### ISSUE THREAD

**Issue by alexwalkercebm** [opensafely/cohort-extractor#71]
We need a safe way to get summary tables, regression results and graphs from the secure server into the public domain, so that researchers can use the outputs and incorporate into papers etc.

The current prototype workflow for this is:
1. Run the analytic (currently Stata) code
2. One person identifies any Stata log files or tables that need to be pushed, then goes through each one to manually redact patient counts of <5.
3. Redaction is done by removing the entire crosstab that contains the data. Examples of tables that have been removed (with modified values) can be found [here](https://github.com/ebmdatalab/opencorona-risk-factors-research/blob/4d301b2df7887654f6f5a329038a77134cdd96d1/analysis/output/redacted_outputs/manually_redacted_table_examples.txt) and below.
4. Another person reviews the same files to check for mistakes, then pushes the redacted files back to GitHub, so that researchers can access them. See [here](https://github.com/ebmdatalab/opencorona-risk-factors-research/tree/4d301b2df7887654f6f5a329038a77134cdd96d1/analysis/output/redacted_outputs) for an example of such a push.

```
     Organ |  Admitted to ITU for
transplant |       Covid-19
 recipient |         0          1 |     Total
-----------+----------------------+----------
         0 |17,406,985        649 |17,407,634 
           |    100.00       0.00 |    100.00 
-----------+----------------------+----------
         1 |    20,125          1 |    20,126 Changed to 1 from real value
           |     99.98       0.02 |    100.00 
-----------+----------------------+----------
     Total |XXXXXXXXXX        XXX |17,427,760 
           |    100.00       0.00 |    100.00 
```

**Comment by sebbacon** [comment]
I think as a first step to a proper implementation we need to write a manual protocol / checklist. Does this already exist @alexwalkercebm?

E.g.

1) Review cross tabs. Does any cell have N < MIN_NUMBER? If so, redact with X
2) Are there any summary counts X / N where either X or N - X is < MIN_NUMBER?
3) Charts
  * Does this chart contain subject-level data (e.g. survival plots)
  * If yes, are any of the numbers depected < MIN_NUMBER?

etc etc

**Comment by sebbacon** [comment]
Current status quo:

Things have got a lot easier since introducing the pipeline, as this requires that users actively opt into publishing outputs as "medium security" / L4 items.  This significantly reduces the review burden.

We have also given lots more people L4 access so they can do the reviewing themselves.

I have developed a protocol which almost no-one has used but me, but which works quite well: a review converts each L4 workspace into a local-only git repo with `git init` and then commits files they want to publish. They can redact and then re-commit as they go. When they are happy with the state of the committed files, they run a script which prompts them for a git remote, and then pushes the current state of the HEAD of the local-only repo as a branch to the remote.

This means subsequent runs will show up in the output of `git diff`, making incremental updates to redacted data easier.

The script is [here](https://github.com/opensafely/output-publisher). It could be altered to take the remote from the local `metadata/` so there's no prompting, and it needs some deployment love to get it available in the PATH of everyone logged into the L4 server.   It also needs documenting.

Beyond this, we still quite urgently need to document a protocol for actually doing the review

**Comment by sebbacon** [comment]
Closed in favour of broken-out issues in linked repos.
